### ISSUE TITLE
ImportError: No module named internet.defer

### ISSUE THREAD

**Issue by DreamFlasher** [ggaughan/pipe2py#33]
I succesfully installed pipe2py and -r requirements.txt. When executing pipe2py/compile.py I am getting the error:
`ImportError: No module named internet.defer`
Which seems to be part of Twisted, but Twisted is succesfully installed.

As Pipes is going to be shut down pipe2py will get a lot of attention, would be great if it were in a state that it is usable with current python installations.

**Comment by DreamFlasher** [comment]
Same problem on unix with anaconda.

**Comment by DreamFlasher** [comment]
Okay looks like this package is stale, here is a fork which at least can be installed: https://github.com/kazeeki/pipe2py (but doesn't run either)

**Comment by ggaughan** [comment]
This is the latest version that I used, perhaps you'll have better luck installing from it if the later branches don't work: 
https://github.com/ggaughan/pipe2py/tree/6a5c31eb218904a17800387bc4cd4239ba1b0b34

**Comment by DreamFlasher** [comment]
Hi Greg,  thanks for your reply! I tried a fresh install of Enthought Canopy and they have an old version of pipe2py in their package manager,  but this fails with a different error (array index should be done with index instead of string; something like this).  
I'd prefer using the latest version and I am super happy to contribute to a fix.  Can you give a bit more information on your setup? Which OS and python distribution are you using? Can you give anaconda a try? 
Thank you!

**Comment by DreamFlasher** [comment]
I've the impression that this issue and issue 31 can be merged.
The error I now get from enthought is: `  File "pipe2py/compile.py", line 44, in <module>
    from pipe2py.modules.pipeforever import pipe_forever
ImportError: No module named pipe2py.modules.pipeforever`

**Comment by ggaughan** [comment]
I'm using Python 2.7.6 on Ubuntu 14.04.2.

Sounds like 'pipeforever' is missing from the list in `pipe2py/modules/__init__.py`

**Comment by DreamFlasher** [comment]
Thank you Greg. As reported in the other thread I installed Ubuntu 14.04.2 and Python 2.7.6, some other things which were missing and still get internet.defer missing error. Can we merge this thread and 31 as they are the same?

**Comment by ggaughan** [comment]
See #31
