### ISSUE TITLE
GAE App Source Code

### ISSUE THREAD

**Issue by Miserlou** [ggaughan/pipe2py#34]
Hey Greg!

Have you released the GAE app source code / instructions?

We currently use Pipes to power our our Glance speed reading applications, and obviously we have to move away from that because they're EOL'ing it.

I'd love to use pipe2py/pipe-engine as a replacement, but I can't seem to find the GAE app code/documentation. 

Is there any chance that you could release it as an open source project, please? 

Thanks!
Rich

**Comment by ggaughan** [comment]
I released a version that ran a pipe on GAE: https://github.com/ggaughan/testpipe

Is that any use to you? If not I could open the more general one - though it's not pretty :)

**Comment by Miserlou** [comment]
I have many pipes, so the more general one would be more useful. Ugly is
okay! :)

**Comment by ggaughan** [comment]
Here it is: https://github.com/ggaughan/pipes-engine
