### ISSUE TITLE
No Module named mezmorize

### ISSUE THREAD

**Issue by nuentes** [ggaughan/pipe2py#37]
I followed the install using sudo.  I'm continually getting an error that mezmorize is not installed.  I found it in ~/pipe2py/src/mezmorize, manually installed dependencies (no errors), and manually installed mezmorize with setup.py, and everything went fine.  But still nose finds 36 errors whenever I test, each error reading "ERROR: Failure: ImportError (No module named mezmorize)"

Ubuntu 14.10, python 2.7

**Comment by ggaughan** [comment]
I suggest you try an earlier version: https://github.com/ggaughan/pipe2py/issues/31#issuecomment-115795527
